---

- name: install rsyslog
  yum:
    name: rsyslog
    state: present

- name: Install SELinux tools
  # required when listening on non-default ports
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - policycoreutils-python
