---

- name: Install rsyslog
  yum:
    name: rsyslog
    state: present

- name: Install libselinux-python
  # required when listening on non-default ports
  yum:
    name: libselinux-python
    state: present

- name: Install policycoreutils-python
  # required when listening on non-default ports
  yum:
    name: policycoreutils-python
    state: present
