---
# handlers file for ansible-role-rsyslog

- name: Restart rsyslog
  service:
    name: "{{ rsyslog_service_name }}"
    state: restarted
    enabled: yes

- name: Restart syslogd
  service:
    name: syslogd
    state: restarted
    enabled: yes
